### ISSUE TITLE
Project Single: Featured image isn't aligned with the sidebar, as per design.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Civil-and-General-Distributors#110]
![image](https://cloud.githubusercontent.com/assets/13363508/15490807/ef8a019c-219d-11e6-9b4d-25954c2520ae.png)

**Comment by ganesh-titan** [comment]
@maehtitan : Please once check this enhancement #105 
As per your requested added some bottom-margin to breadcrumbs because it's too close to featured image.Let me know once if you need as per design and change the label to enhancement.

Thank you.

**Comment by maehtitan** [comment]
@ganesh-titan The issue you were referring is to adjust the spaces after the breadcrumbs coz they are too close with the featured image below. But this issue different the sidebar and the featured image must be aligned to each other.

Title must occupy the whole width as what the design implies just like the sample grid below


![image](https://cloud.githubusercontent.com/assets/13363508/15697420/7da590b4-27ec-11e6-828b-e730d642a3b7.png)

**Comment by ganesh-titan** [comment]
Updated
