### ISSUE TITLE
Gallery Single page - images are not all aligned as per design

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/Civil-and-General-Distributors#12]
![image](https://cloud.githubusercontent.com/assets/17717843/15170890/8fe472e8-177c-11e6-883d-4ce0eb0c31c4.png)

**Comment by ganesh-titan** [comment]
FYI: Please upload new images with minimum these dimensions width:189px and height:144px.

**Comment by dremensayson** [comment]
Hi Ganesh,
Please add image container so that even if user uploaded small or large image it will fit in the container and retain the aspect ratio so that the image will not pixelated.
