### ISSUE TITLE
Custom Fields - Brand Gallery, Our Staff, Testimonial Group, Projects Group & Home Page Settings: Page attributes shouldn't be hidden.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Civil-and-General-Distributors#13]
https://knowledgebase.titanweb.com.au/implementation/advanced-custom-fields-implementation/advanced-custom-fields-options
![image](https://cloud.githubusercontent.com/assets/13363508/15171125/917a61f6-177e-11e6-9d8f-0b8eab402fa8.png)

**Comment by ganesh-titan** [comment]
Hi,
I think Page attributes  should be HIDDEN !
Updated. 

Thankyou
