### ISSUE TITLE
Our Range: Missing parent category of Commercial Kitchen Drains and Stainless Steel Grates Bathroom 

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Civil-and-General-Distributors#132]
![image](https://cloud.githubusercontent.com/assets/13363508/15696656/1001d7f4-27e5-11e6-891f-a8d4879435fa.png)
![image](https://cloud.githubusercontent.com/assets/13363508/15696898/8393a4c0-27e7-11e6-9f7b-b14d2472be50.png)

**Comment by ganesh-titan** [comment]
@maehtitan  : please check once related issue  #133

**Comment by maehtitan** [comment]
@ganesh-titan Will marked this one as fixed coz in the first place only the parent category must be shown but you have implemented it to show subcategory.
