### ISSUE TITLE
Our Range: If a category has a sub-category it must be indented and must not line up with the parent category.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Civil-and-General-Distributors#133]
![image](https://cloud.githubusercontent.com/assets/13363508/15696675/6868ea40-27e5-11e6-9ba6-bb2bf79bd7f5.png)

**Comment by ganesh-titan** [comment]
@maehtitan : After discussing with my TL, we removed the accordion functionality because scope has noted that point.  
![sidebar_categorires](https://cloud.githubusercontent.com/assets/13450883/15743754/4e82640c-28e5-11e6-94f0-60823ec95c9b.jpg)

**Comment by maehtitan** [comment]
@ganesh-titan Will marked this one as fixed coz in the first place only the parent category must be shown but you have implemented it to show subcategory.
