### ISSUE TITLE
Heading Font Sizes: Where did you get your H2 heading font-size? I prefer you must follow the Our Staff font-size.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Civil-and-General-Distributors#17]
![image](https://cloud.githubusercontent.com/assets/13363508/15171540/e128181c-1781-11e6-91a3-1d10a729acd3.png)

**Comment by ganesh-titan** [comment]
![screen-shot-2016-05-13-at-18 54](https://cloud.githubusercontent.com/assets/13450883/15249367/cc1aa338-193c-11e6-8299-d70ab9a3878c.jpg)

Hi, I get it from About us page sub heading.

**Comment by maehtitan** [comment]
Thanks :)
