### ISSUE TITLE
Gallery: pagination is not implemented

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/Civil-and-General-Distributors#21]
![image](https://cloud.githubusercontent.com/assets/17717843/15171948/19116276-1785-11e6-8e6e-8f8ee285b9dc.png)

**Comment by ganesh-titan** [comment]
Hi,
For this pagination we need to change plugin files.but we have no access to change plugin files.Please suggest me if you know any reference link provide me.

Thank you.

**Comment by maehtitan** [comment]
@ganesh-titan Will mark this one as wontfix for the moment but please update the scope. 

Thanks

**Comment by maehtitan** [comment]
@ganesh-titan Project Scope isn't updated yet.
![image](https://cloud.githubusercontent.com/assets/13363508/15489863/f471b9be-2195-11e6-8f7e-05de3b1a1ae5.png)

**Comment by ganesh-titan** [comment]
Hi,
Waiting for response from TL

**Comment by maehtitan** [comment]
@ganesh-titan you can comment in Issues section here: https://docs.google.com/spreadsheets/d/1EC9fGX4Y1YebQQNV_4A7hsOkaH7zC3k8d4MtYsIr8iQ/edit?pref=2&pli=1#gid=2035631399

**Comment by ganesh-titan** [comment]
Updated my comment.
