### ISSUE TITLE
Banner Section: Banner should be paused on hover when there are text contents/buttons added

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Civil-and-General-Distributors#23]
https://knowledgebase.titanweb.com.au/development-2016/development-modules-development-2016/banners
![image](https://cloud.githubusercontent.com/assets/13363508/15172124/5d70c37a-1786-11e6-9e40-9dca4248c3ec.png)

**Comment by maehtitan** [comment]
@ganesh-titan Pause on Hover still not fixed.

**Comment by maehtitan** [comment]
No changes has been made. Image still moving when hovered.

**Comment by ganesh-titan** [comment]
Updated.
