### ISSUE TITLE
Read More - Global Buttons: Please remove fall back as per Standard and Guidelines G-33.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Civil-and-General-Distributors#35]
![image](https://cloud.githubusercontent.com/assets/13363508/15173568/56ff40e4-178f-11e6-8998-d1d07144f6de.png)
![image](https://cloud.githubusercontent.com/assets/13363508/15173816/d1562a5a-1790-11e6-936f-4edd233625d0.png)

**Comment by ganesh-titan** [comment]
Hi,
If there is no label , we can't navigate to the single page.Please let me know any suggestion ?
Thank you.

**Comment by maehtitan** [comment]
Hi @ganesh-titan,

Please make the title clickable instead.

Thanks

**Comment by ganesh-titan** [comment]
Hi,
Updated Recent News section, Projects , News/blog and Leadins.

Thank you.
