### ISSUE TITLE
Homepage - Please change the name of the tab in the CMS from Meet our team to Recent News

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/Civil-and-General-Distributors#41]
![image](https://cloud.githubusercontent.com/assets/17717843/15176370/55785536-179d-11e6-9e2e-ba69da809012.png)

**Comment by ganesh-titan** [comment]
Hi,
As per scope we are implemented.
![news-tab](https://cloud.githubusercontent.com/assets/13450883/15291651/a6bd0d30-1b9c-11e6-9fcc-5c198d7a25ce.jpg)

**Comment by dremensayson** [comment]
Hi Ganesh,
please see screenshots below, as per kyla request.
![img_17052016_152425](https://cloud.githubusercontent.com/assets/17717843/15314380/072b0684-1c44-11e6-8760-127c2f6edd47.png)

but if you notice the page section label is  not matched with the tab label that you implemented in the backend, this can caused confusion to the user.

**Comment by ganesh-titan** [comment]
Hi, Updated.
Thank you.
