### ISSUE TITLE
Product Application: Not implemented as per scope.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Civil-and-General-Distributors#42]
![image](https://cloud.githubusercontent.com/assets/13363508/15176310/10052132-179d-11e6-9321-20dd7cf7e75b.png)

**Comment by ganesh-titan** [comment]
Hi,
After discussion with my TL,  "Product Application" is  one of the category of Woo commerce with comparing the design.so am assigned 1 category to main menu.

Thank you.

**Comment by maehtitan** [comment]
Hi @ganesh-titan 

It was Kayla request. Checked the product category but no Product Applications added.

![image](https://cloud.githubusercontent.com/assets/13363508/15381544/ee6db3ec-1db2-11e6-8576-04fb29fa14b9.png)

**Comment by ganesh-titan** [comment]
Hi,
Scope updated.

**Comment by maehtitan** [comment]
@ganesh-titan Yes,Scope is updated, but the Menu Appearance "Product Applications" and slug doesn't matched with the Page title "Miscellaneous". Is it the final content is the Category "Miscellaneous"?

**Comment by ganesh-titan** [comment]
Hi,
Waiting for response from TL

**Comment by ganesh-titan** [comment]
@maehtitan : No, Product Applications is one of the category ( specific category highlighted to main menu ) of woo-commerce. We have to add some products to this category.
