### ISSUE TITLE
Product categories - Please re-order the menu on the categories page (left menu) to be in the same order as per the CMS

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/Civil-and-General-Distributors#44]
![image](https://cloud.githubusercontent.com/assets/17717843/15176688/d33dc9f0-179e-11e6-9896-755e5c9a8ba6.png)

**Comment by ganesh-titan** [comment]
FYI: If u create any new category we need to assign at least 1 product then display the category.
Thank you.

**Comment by dremensayson** [comment]
Hi Ganesh,
Yes, we know that the category should have at least 1 product to displayed in the menu, but as you can see in the screenshot above Test Category already displayed in the Sidebar Menu even if it has no product. So please implement not to display the category if no product both in sidebar and grid view.

**Comment by ganesh-titan** [comment]
Hi, Updated.
