### ISSUE TITLE
Titan Options: When field is blank, no WP default placeholder applied as per scope.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Civil-and-General-Distributors#54]
![image](https://cloud.githubusercontent.com/assets/13363508/15201888/25af7b14-1828-11e6-8f0e-95cceb211ea2.png)

![image](https://cloud.githubusercontent.com/assets/13363508/15201884/14a63f60-1828-11e6-826e-9e5ef67c2716.png)

**Comment by maehtitan** [comment]
@ganesh-titan not yet fixed. please implement it like the sample site below currently no image has been shown after deleting the default no-image.
![image](https://cloud.githubusercontent.com/assets/13363508/15381725/c467ccde-1db4-11e6-81d9-20a7e05403f7.png)
![image](https://cloud.githubusercontent.com/assets/13363508/15381742/ee3ec3be-1db4-11e6-9f24-b20d8a38712b.png)

**Comment by ganesh-titan** [comment]
Updated.

**Comment by maehtitan** [comment]
@ganesh-titan It is only fixed in the News / Blog only. It is not fixed in these pages
![image](https://cloud.githubusercontent.com/assets/13363508/15490463/d116e6f6-219a-11e6-96cb-6fa7f29c76d9.png)
![image](https://cloud.githubusercontent.com/assets/13363508/15490481/f94c4788-219a-11e6-8aa0-8154242dda49.png)
![image](https://cloud.githubusercontent.com/assets/13363508/15490491/0c07e2ec-219b-11e6-8e9d-9c1831614a2d.png)

It is global so please fix in the affected pages with default no-image.
