### ISSUE TITLE
Projects Single: images are not responsive.

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/Civil-and-General-Distributors#55]
![image](https://cloud.githubusercontent.com/assets/17717843/15202249/33843a38-182b-11e6-8b0f-5d39e82a4e14.png)

Please follow implementation of this sample site:
http://junglegym-2016.stage.titanweb.com.au/toodler-play/

**Comment by iteano** [comment]
Not fixed. At 991px viewport image overlaps with the breadcrumbs and thumbnails.
