### ISSUE TITLE
Sidebar: Remove the sidebar form tab in titan option because this is unnecessary field, when field is empty the sidebar form still visible in the site.

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/Civil-and-General-Distributors#65]
![image](https://cloud.githubusercontent.com/assets/17717843/15203390/c5061224-1835-11e6-9e2d-5b705d875672.png)

**Comment by ganesh-titan** [comment]
Hi, Removed form tab from titan options and as per default sidebar form is coming from Widget.
Thank you.
