### ISSUE TITLE
Admin - Banner Custom Post: No pages found when clicking the button link ACF, I believe the Get In Touch button link is hard-coded.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Civil-and-General-Distributors#68]
![image](https://cloud.githubusercontent.com/assets/13363508/15203520/2d46d1e2-1837-11e6-9df0-b2b2a647b049.png)

**Comment by maehtitan** [comment]
Still no pages found when clicking field.
![image](https://cloud.githubusercontent.com/assets/13363508/15381920/b0d0e46a-1db6-11e6-9685-10375bcbd7b3.png)

**Comment by ganesh-titan** [comment]
Hi,
Banner Links ACF field has been Removed.Get in touch link assigned to titan options.

Thank you.
