### ISSUE TITLE
Leadins - Responsive Checking: Leadins are hidden. Please see the video url below.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Civil-and-General-Distributors#76]
http://screencast.com/t/1QTplwKa

![image](https://cloud.githubusercontent.com/assets/13363508/15205331/d8409aa4-1848-11e6-9e56-69266ee46e25.png)

**Comment by ganesh-titan** [comment]
Hi,
Discussed with my TL Waiting for update.

**Comment by maehtitan** [comment]
@ganesh-titan Please fix also in the Recent News carousel same issue occurs.
