### ISSUE TITLE
Contact Us: Is the featured image supposed to be enabled? Because It is mentioned in the project scope.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Civil-and-General-Distributors#8]
![image](https://cloud.githubusercontent.com/assets/13363508/15169334/b3b6a746-176c-11e6-9438-79c9593def52.png)
![image](https://cloud.githubusercontent.com/assets/13363508/15169351/e4669748-176c-11e6-9580-d88f52208bf2.png)

**Comment by ganesh-titan** [comment]
Hi , Updated as per scope.
Thanks.
