### ISSUE TITLE
Homepage - Recent News: There is a white layout below the "View More" button.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Civil-and-General-Distributors#81]
![image](https://cloud.githubusercontent.com/assets/13363508/15205940/fc1c768c-184d-11e6-9cee-2162dad8bf6b.png)

**Comment by maehtitan** [comment]
White layout is still there.
![image](https://cloud.githubusercontent.com/assets/13363508/15383738/ce377aa8-1dc7-11e6-9d5f-8a2ddae32f68.png)

**Comment by ganesh-titan** [comment]
@maehtitan , I have tested all browsers but i didn't get any extra space. As per design hight 53px. currently it's shown 53px
